
--***************************************************
--	All schema DDL (initial - after import to Exadata APEX 4.1.1) 
--	added on 11/8/2012
--****************************************************

-- Tables
CREATE TABLE "RMGR"."RLSMGR_STATUSES"
  (
    "STATUS_ID"   NUMBER(2,0) NOT NULL ENABLE,
    "STATUS_DESC" VARCHAR2(50 BYTE) NOT NULL ENABLE,
    CONSTRAINT "RLSMGR_STATUSES_PK" PRIMARY KEY ("STATUS_ID")
  );
  
CREATE TABLE "RMGR"."RLSMGR_FORM_TYPES"
  (
    "FORM_TYPE_ID"   NUMBER(2,0) NOT NULL ENABLE,
    "FORM_TYPE_DESC" VARCHAR2(50 BYTE),
    CONSTRAINT "RLSMGR_FORM_TYPES_PK" PRIMARY KEY ("FORM_TYPE_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "USERS" ENABLE
  );

CREATE TABLE "RMGR"."RLSMGR_FORMS"
  (
    "FORM_ID"      NUMBER(5,0) NOT NULL ENABLE,
    "PRJMGR_ID"    NUMBER(2,0) NOT NULL ENABLE,
    "FORM_TYPE_ID" NUMBER(2,0) NOT NULL ENABLE, 
    "POPULATION_DATE" DATE NOT NULL ENABLE,
    "LAST_UPDATE_DATE" DATE,
    "BUGZILLA_ID"    NUMBER(5,0) NOT NULL ENABLE,
    "RM_BUGZILLA_ID" NUMBER(5,0),
    "TASK_NAME"      VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "SHORT_DESC"     VARCHAR2(500 BYTE) NOT NULL ENABLE,
    "STATUS_ID"      NUMBER(2,0),
    CONSTRAINT "RLSMGR_FORMS_PK" PRIMARY KEY ("FORM_ID"),
    CONSTRAINT "RLSMGR_FORMS_CON" UNIQUE ("BUGZILLA_ID"),
    CONSTRAINT "RLSMGR_STATUSID_FK" FOREIGN KEY ("STATUS_ID") REFERENCES "RMGR"."RLSMGR_STATUSES" ("STATUS_ID") ENABLE,
	CONSTRAINT RLSMGR_FORMTYP_FK FOREIGN KEY(FORM_TYPE_ID) REFERENCES RMGR.RLSMGR_FORM_TYPES(FORM_TYPE_ID) ENABLE
  );
CREATE UNIQUE INDEX "RMGR"."RLSMGR_FORMS_PK" ON "RMGR"."RLSMGR_FORMS"
  (
    "FORM_ID"
  );
CREATE UNIQUE INDEX "RMGR"."RLSMGR_FORMS_CON" ON "RMGR"."RLSMGR_FORMS"
  (
    "BUGZILLA_ID"
  );

CREATE TABLE "RMGR"."RLSMGR_AREAS"
  (
    "AREA_ID"   NUMBER(2,0) NOT NULL ENABLE,
    "AREA_DESC" VARCHAR2(50 BYTE),
    CONSTRAINT "RLSMGR_AREAS_PK" PRIMARY KEY ("AREA_ID")
  );

CREATE TABLE "RMGR"."RLSMGR_OBJ_TYPES"
  (
    "OBJ_TYPE_ID"   NUMBER(2,0) NOT NULL ENABLE,
    "OBJ_TYPE_DESC" VARCHAR2(50 BYTE),
    CONSTRAINT "RLSMGR_OBJ_TYPES_PK" PRIMARY KEY ("OBJ_TYPE_ID")
  );
  
CREATE TABLE "RMGR"."RLSMGR_OBJECTS"
  (
    "OBJ_ID"      NUMBER(5,0) NOT NULL ENABLE,
    "OBJ_DESC"    VARCHAR2(100 BYTE),
    "OBJ_TYPE_ID" NUMBER(2,0) NOT NULL ENABLE,
    "OBJ_AREA_ID" NUMBER(2,0) NOT NULL ENABLE,
    "FORM_ID"     NUMBER(5,0),
    CONSTRAINT "RLSMGR_OBJECTS_UNQ" UNIQUE ("OBJ_DESC", "OBJ_AREA_ID", "OBJ_TYPE_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS STORAGE(INITIAL 1310720 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "RLSMGR_OBJECTS_PK" PRIMARY KEY ("OBJ_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS STORAGE(INITIAL 589824 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "RLSMGR_OBJAREA_FK" FOREIGN KEY ("OBJ_AREA_ID") REFERENCES "RMGR"."RLSMGR_AREAS" ("AREA_ID") ENABLE,
    CONSTRAINT "RLSMGR_OBJTYPES_FK" FOREIGN KEY ("OBJ_TYPE_ID") REFERENCES "RMGR"."RLSMGR_OBJ_TYPES" ("OBJ_TYPE_ID") ENABLE,
    CONSTRAINT "RLSMGR_FORMID_FK" FOREIGN KEY ("FORM_ID") REFERENCES "RMGR"."RLSMGR_FORMS" ("FORM_ID") ENABLE NOVALIDATE
  );
CREATE UNIQUE INDEX "RMGR"."RLSMGR_OBJECTS_UNQ" ON "RMGR"."RLSMGR_OBJECTS"
  (
    "OBJ_DESC", "OBJ_AREA_ID", "OBJ_TYPE_ID"
  );
CREATE UNIQUE INDEX "RMGR"."RLSMGR_OBJECTS_PK" ON "RMGR"."RLSMGR_OBJECTS"
  (
    "OBJ_ID"
  );
  
CREATE TABLE "RMGR"."RLSMGR_AREAS_TO_OBJTYPES"
  (
    "AREA_ID"     NUMBER(2,0) NOT NULL ENABLE,
    "OBJ_TYPE_ID" NUMBER(2,0) NOT NULL ENABLE,
    CONSTRAINT "RLSMGR_AREAS_TO_OBJTYPES_PK" PRIMARY KEY ("AREA_ID", "OBJ_TYPE_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "OBJ_TYPE_ID_FK" FOREIGN KEY ("OBJ_TYPE_ID") REFERENCES "RMGR"."RLSMGR_OBJ_TYPES" ("OBJ_TYPE_ID") ENABLE,
    CONSTRAINT "AREA_ID_FK" FOREIGN KEY ("AREA_ID") REFERENCES "RMGR"."RLSMGR_AREAS" ("AREA_ID") ENABLE
  );  
  
CREATE TABLE "RMGR"."RLSMGR_FORMCHANGESOBJS"
  (
    "FORM_ID"        NUMBER(5,0) NOT NULL ENABLE,
    "OBJ_ID"         NUMBER(5,0) NOT NULL ENABLE,
    "CHANGE_DETAILS" VARCHAR2(4000 BYTE),
    CONSTRAINT "RLSMGR_FORMCHANGESOBJS_PK" PRIMARY KEY ("FORM_ID", "OBJ_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "RLSMGR_FORMCHANGESOBJS_CON2" FOREIGN KEY ("OBJ_ID") REFERENCES "RMGR"."RLSMGR_OBJECTS" ("OBJ_ID") ENABLE,
    CONSTRAINT "RLSMGR_FORMCHANGESOBJS_CON" FOREIGN KEY ("FORM_ID") REFERENCES "RMGR"."RLSMGR_FORMS" ("FORM_ID") ENABLE
  ); 

CREATE TABLE "RMGR"."RLSMGR_FORMREFERSTOAREAS"
  (
    "FORM_ID" NUMBER(5,0) NOT NULL ENABLE,
    "AREA_ID" NUMBER(2,0) NOT NULL ENABLE,
    CONSTRAINT "RLSMGR_FORMREFERSTOAREAS_UK1" UNIQUE ("FORM_ID", "AREA_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "RLSMGR_FORMREFERSTOAREAS_FK2" FOREIGN KEY ("AREA_ID") REFERENCES "RMGR"."RLSMGR_AREAS" ("AREA_ID") ENABLE,
    CONSTRAINT "RLSMGR_FORMREFERSTOAREAS_FK1" FOREIGN KEY ("FORM_ID") REFERENCES "RMGR"."RLSMGR_FORMS" ("FORM_ID") ENABLE
  );
CREATE UNIQUE INDEX "RMGR"."RLSMGR_FORMREFERSTOAREAS_UK1" ON "RMGR"."RLSMGR_FORMREFERSTOAREAS"
  (
    "FORM_ID", "AREA_ID"
  );  

CREATE TABLE "RMGR"."RLSMGR_PRJ_MANAGERS"
  (
    "PRJMGR_ID"    NUMBER(2,0) NOT NULL ENABLE,
    "PRJMGR_FNAME" VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "PRJMGR_LNAME" VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "PRJMGR_EMAIL" VARCHAR2(50 BYTE) NOT NULL ENABLE,
    CONSTRAINT "RLSMGR_PRJ_MANAGERS_PK" PRIMARY KEY ("PRJMGR_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "USERS" ENABLE
  );

-- Views
CREATE OR REPLACE FORCE VIEW "RMGR"."RLSMGR_FORMCHANGESOVJS_V" ("FORM_ID", "OBJ_ID", "OBJ_DESC", "AREA_ID", "AREA_DESC")
AS
  SELECT a.FORM_ID FORM_ID,
    a.OBJ_ID OBJ_ID,
    d.obj_desc OBJ_DESC,
    e.AREA_ID AREA_ID,
    e.AREA_DESC AREA_DESC
  FROM RMGR.RLSMGR_FORMCHANGESOBJS a
  JOIN RMGR.RLSMGR_FORMS b
  ON (a.form_id = b.form_id)
  JOIN RMGR.RLSMGR_OBJECTS d
  ON (a.obj_id = d.obj_id)
  JOIN RMGR.RLSMGR_AREAS e
  ON(d.OBJ_AREA_ID = e.AREA_ID) ;

 -- sequences
CREATE SEQUENCE "RMGR"."RLSMGR_AREAS_SEQ" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER NOCYCLE ;
CREATE SEQUENCE "RMGR"."RLSMGR_FORM_TYPES_SEQ" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER NOCYCLE ;
CREATE SEQUENCE "RMGR"."RLSMGR_FORMS_SEQ" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 2262 CACHE 20 NOORDER NOCYCLE ;
CREATE SEQUENCE "RMGR"."RLSMGR_OBJ_TYPES_SEQ" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER NOCYCLE ;
CREATE SEQUENCE "RMGR"."RLSMGR_OBJECTS_SEQ" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21462 CACHE 20 NOORDER NOCYCLE ;
CREATE SEQUENCE "RMGR"."RLSMGR_PRJ_MANAGERS_SEQ" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER NOCYCLE ;
CREATE SEQUENCE "RMGR"."RLSMGR_STATUSES_SEQ" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE ;
  
 --Triggers  
CREATE OR REPLACE TRIGGER "RMGR"."BI_RLSMGR_FORMS" before
  INSERT ON "RLSMGR_FORMS" FOR EACH row BEGIN IF :NEW."FORM_ID" IS NULL THEN
  SELECT "RLSMGR_FORMS_SEQ".nextval INTO :NEW."FORM_ID" FROM dual;
END IF;
END;
/
ALTER TRIGGER "RMGR"."BI_RLSMGR_FORMS" ENABLE;

CREATE OR REPLACE TRIGGER "RMGR"."BI_RLSMGR_AREAS" before
  INSERT ON "RLSMGR_AREAS" FOR EACH row BEGIN IF :NEW."AREA_ID" IS NULL THEN
  SELECT "RLSMGR_AREAS_SEQ".nextval INTO :NEW."AREA_ID" FROM dual;
END IF;
END;
/
ALTER TRIGGER "RMGR"."BI_RLSMGR_AREAS" ENABLE;

CREATE OR REPLACE TRIGGER "RMGR"."BI_RLSMGR_OBJ_TYPES" before
  INSERT ON "RLSMGR_OBJ_TYPES" FOR EACH row BEGIN IF :NEW."OBJ_TYPE_ID" IS NULL THEN
  SELECT "RLSMGR_OBJ_TYPES_SEQ".nextval INTO :NEW."OBJ_TYPE_ID" FROM dual;
END IF;
END;
/
ALTER TRIGGER "RMGR"."BI_RLSMGR_OBJ_TYPES" ENABLE;  

CREATE OR REPLACE TRIGGER "RMGR"."BI_RLSMGR_OBJECTS" before
  INSERT ON "RLSMGR_OBJECTS" FOR EACH row BEGIN IF :NEW."OBJ_ID" IS NULL THEN
  SELECT "RLSMGR_OBJECTS_SEQ".nextval INTO :NEW."OBJ_ID" FROM dual;
END IF;
END;
/
ALTER TRIGGER "RMGR"."BI_RLSMGR_OBJECTS" ENABLE;  

CREATE OR REPLACE TRIGGER "RMGR"."BI_RLSMGR_FORM_TYPES" before
  INSERT ON "RLSMGR_FORM_TYPES" FOR EACH row BEGIN IF :NEW."FORM_TYPE_ID" IS NULL THEN
  SELECT "RLSMGR_FORM_TYPES_SEQ".nextval INTO :NEW."FORM_TYPE_ID" FROM dual;
END IF;
END;
/
ALTER TRIGGER "RMGR"."BI_RLSMGR_FORM_TYPES" ENABLE;  

CREATE OR REPLACE TRIGGER "RMGR"."BI_RLSMGR_PRJ_MANAGERS" before
  INSERT ON "RLSMGR_PRJ_MANAGERS" FOR EACH row BEGIN IF :NEW."PRJMGR_ID" IS NULL THEN
  SELECT "RLSMGR_PRJ_MANAGERS_SEQ".nextval INTO :NEW."PRJMGR_ID" FROM dual;
END IF;
END;
/
ALTER TRIGGER "RMGR"."BI_RLSMGR_PRJ_MANAGERS" ENABLE;  

--***************************************************
--	Additions to support the "release concept"
--	added on 11/8/2012
--****************************************************

-- ayto eixe ξεχαστεί και απλά το προσθέτω τώρα 
alter table rlsmgr_forms add constraint RLSMGR_FORMTYP_FK FOREIGN KEY(FORM_TYPE_ID) REFERENCES RMGR.RLSMGR_FORM_TYPES(FORM_TYPE_ID);

-- NEW TABLES

-- New table RELEASE_TYPES
create table RMGR.RLSMGR_RLS_TYPES
(
	RLS_TYPE_CODE VARCHAR2(3) PRIMARY KEY,
	RLS_TYPE_DESC VARCHAR2(100)
);
COMMENT ON TABLE RMGR.RLSMGR_RLS_TYPES IS 'Stores the various release types: Major release, Minor release, Hot-Fix etc.';

--alter table RELEASE_TYPES rename  to RLSMGR_RLS_TYPES

insert into RMGR.RLSMGR_RLS_TYPES
values ('MJ','Major Release');
insert into RMGR.RLSMGR_RLS_TYPES
values ('MN','Minor Release');
insert into RMGR.RLSMGR_RLS_TYPES
values ('HF','Hot-Fix');
commit;

-- New table RELEASES
create table RMGR.RLSMGR_RELEASES
(
		RLS_ID	NUMBER(5,0) NOT NULL,
		RLS_NAME VARCHAR2(20) NOT NULL ,
		RLS_DESC VARCHAR2(4000),
		TARGET_DEPLOY_DATE	DATE NOT NULL,
		ACTUAL_DEPLOY_DATE	DATE,
		RLS_TYPE_CODE  VARCHAR2(3) NOT NULL, 
		RLS_CODE_FOLDER VARCHAR2(4000),
		constraint RLS_PK PRIMARY KEY(RLS_ID),
		constraint RLS_UNQ UNIQUE(RLS_NAME),
		CONSTRAINT RLS_TYPE_FK FOREIGN KEY(RLS_TYPE_CODE) REFERENCES RMGR.RLSMGR_RLS_TYPES(RLS_TYPE_CODE)
);
COMMENT ON TABLE RMGR.RLSMGR_RELEASES IS 'Each row represents a unique release';
COMMENT ON COLUMN RMGR.RLSMGR_RELEASES.RLS_NAME IS 'Release name is of the form: TARGET_DATE(YYYYMMDD).RLS_TYPE_CODE.RLS_ID';  

CREATE SEQUENCE "RMGR"."RLSMGR_RLS_SEQ" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE ;

--alter table RELEASES rename  to RLSMGR_RELEASES
-- trigger for generating PKs
CREATE OR REPLACE TRIGGER "RMGR"."TRG_RLSMGR_RLS" before INSERT ON "RLSMGR_RELEASES" FOR EACH row 
BEGIN 
	IF :NEW."RLS_ID" IS NULL THEN
		SELECT "RLSMGR_RLS_SEQ".nextval INTO :NEW."RLS_ID" FROM dual;
		
		-- generate also the Release Name
		IF :NEW.TARGET_DEPLOY_DATE IS NOT NULL and :NEW.RLS_TYPE_CODE IS NOT NULL THEN
			:NEW.RLS_NAME := to_char(:NEW.TARGET_DEPLOY_DATE,'YYYYMMDD')||'.'||:NEW.RLS_TYPE_CODE||'.'||lpad(:NEW.RLS_ID,5,'0');
		END IF;
	END IF;
END;
/
ALTER TRIGGER "RMGR"."TRG_RLSMGR_RLS" ENABLE;

-- create a dummy release
insert into RLSMGR_RELEASES(		
		RLS_DESC,
		TARGET_DEPLOY_DATE,
		ACTUAL_DEPLOY_DATE,
		RLS_TYPE_CODE, 
		RLS_CODE_FOLDER
)
values(	
	'This is a dummy release',
	to_date('1999/12/31','yyyy/mm/dd'),
	null,
	'MJ',
	null
);		
commit;
-- a CR can belong to one and only one Release, i.e., CRs: RELEASEs ==> N:1
-- add the corresponding FL column to FORMS table
alter table RMGR.RLSMGR_FORMS add RLS_ID NUMBER(5,0) DEFAULT 1;
alter table RMGR.RLSMGR_FORMS add CONSTRAINT RLSMGR_RLS_FK FOREIGN KEY (RLS_ID) REFERENCES RMGR.RLSMGR_RELEASES(RLS_ID);
COMMENT ON COLUMN RMGR.RLSMGR_FORMS.RLS_ID IS 'Points to the release where this CR belongs';

/*
update RMGR.RLSMGR_FORMS
set RLS_ID = 1
where RLS_ID is null;

commit;

*/

--***************************************************
--	added on 13/8/2012
--****************************************************

create index RMGR.RLS_ID_FK_IDX on RMGR.RLSMGR_FORMS(RLS_ID) compute statistics;

-- create a simple security (authorization) scheme
create table RMGR.RLMGR_AUTH_SCHEMES
(
username varchar2(50),
role	 varchar2(50)
);

insert into RMGR.RLMGR_AUTH_SCHEMES (username, role) values('nkarag', 'rls_manager');
insert into RMGR.RLMGR_AUTH_SCHEMES (username, role) values('sgiantsou', 'rls_manager');
insert into RMGR.RLMGR_AUTH_SCHEMES (username, role) values('admin', 'rls_manager');
insert into RMGR.RLMGR_AUTH_SCHEMES (username, role) values('lsinos', 'rls_manager');
insert into RMGR.RLMGR_AUTH_SCHEMES (username, role) values('standby_bi', 'developer');
insert into RMGR.RLMGR_AUTH_SCHEMES (username, role) values('viewer', 'viewer');
insert into RMGR.RLMGR_AUTH_SCHEMES (username, role) values('dw_developer', 'developer');

commit;


--***************************************************
--	added on 16/8/2012
--****************************************************
alter table RLSMGR_FORMS modify task_name varchar2(4000);         

alter table RLSMGR_FORMS modify short_desc varchar2(4000);

--***************************************************
--	added on 20/05/2014 (revision 10)
--****************************************************
create table RLSMGR_FORMS2RELEASES_MAP (
    rls_id number(5),
    form_id number(5)
);

alter table RLSMGR_FORMS2RELEASES_MAP add constraint RLSMGR_FORMS2RELEASES_MAP_PK  primary key(rls_id, form_id);

alter table RLSMGR_FORMS2RELEASES_MAP add constraint RLSMGR_FORMS2RELEASES_MAP_FK1 foreign key(rls_id) references RLSMGR_RELEASES(RLS_ID);
alter table RLSMGR_FORMS2RELEASES_MAP add constraint RLSMGR_FORMS2RELEASES_MAP_FK2 foreign key(form_id) references RLSMGR_FORMS(FORM_ID);

insert into RLSMGR_FORMS2RELEASES_MAP
SELECT RLS_ID,
  /*RLS_NAME,
  RLS_DESC,
  TARGET_DEPLOY_DATE,
  ACTUAL_DEPLOY_DATE,  
  RLS_CODE_FOLDER,
  BUGZILLA_ID,
  rlsmgr_forms.task_name,*/
  rlsmgr_forms.form_id
FROM RLSMGR_RELEASES JOIN rlsmgr_forms using(RLS_ID) 
ORDER BY RLS_NAME DESC, BUGZILLA_ID DESC;

commit;