
drop user RMGR;
CREATE USER RMGR PROFILE "DEFAULT" IDENTIFIED BY rmgr ACCOUNT UNLOCK;

GRANT CONNECT TO RMGR;
GRANT CREATE TABLE TO RMGR;
GRANT CREATE PROCEDURE to RMGR;

drop user RMGR;

alter user RMGR identified by rmgr

CREATE USER RMGR
  IDENTIFIED BY VALUES rmgr
  DEFAULT TABLESPACE SCRATCH
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 1 Role for RMGR 
  GRANT CONNECT TO RMGR;
  ALTER USER RMGR DEFAULT ROLE ALL;
  -- 14 System Privileges for RMGR 
  GRANT CREATE JOB TO RMGR;
  GRANT CREATE SEQUENCE TO RMGR;
  GRANT CREATE TYPE TO RMGR;
  GRANT CREATE MATERIALIZED VIEW TO RMGR;
  GRANT CREATE DIMENSION TO RMGR;
  GRANT CREATE INDEXTYPE TO RMGR;
  GRANT CREATE OPERATOR TO RMGR;
  GRANT CREATE VIEW TO RMGR;
  GRANT CREATE TABLE TO RMGR;
  GRANT CREATE TRIGGER TO RMGR;
  GRANT CREATE ANY CONTEXT TO RMGR;
  GRANT CREATE PROCEDURE TO RMGR;
  GRANT CREATE SYNONYM TO RMGR;
  GRANT CREATE CLUSTER TO RMGR;
  -- 1 Tablespace Quota for RMGR 
  ALTER USER RMGR QUOTA UNLIMITED ON SCRATCH;
  -- 3 Object Privileges for RMGR 
    GRANT EXECUTE ON  CTXSYS.CTX_DDL TO RMGR;
    GRANT EXECUTE ON  CTXSYS.CTX_DOC TO RMGR;
    GRANT EXECUTE ON  SYS.DBMS_RLS TO RMGR;